[package]
name = "bench-lea-mov-array"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.3"
# rand = "0.8.5"

[build-dependencies]
rand = "0.8.5"

[[bench]]
name = "doit"
harness = false
