name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bench:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux-amd64, linux32, macos, win32, win64, mingw32, mingw64]
        include:
          - build: linux-amd64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: linux32
            os: ubuntu-latest
            target: i686-unknown-linux-gnu
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
          - build: win32
            os: windows-2016
            target: i686-pc-windows-msvc
          - build: win64
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - build: mingw32
            os: windows-latest
            target: i686-pc-windows-gnu
          - build: mingw64
            os: windows-latest
            target: x86_64-pc-windows-gnu
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      run: |
        rustup default nightly-${{ matrix.target }}
      shell: bash
    - name: Install g++-multilib
      run: |
        set -e
        # Remove the ubuntu-toolchain-r/test PPA, which is added by default.
        # Some packages were removed, and this is causing the g++multilib
        # install to fail. Similar issue:
        # https://github.com/scikit-learn/scikit-learn/issues/13928.
        sudo add-apt-repository --remove ppa:ubuntu-toolchain-r/test
        sudo apt-get install g++-multilib
      shell: bash
      if: matrix.build == 'linux32'

    - name: Rust Version
      run: |
        rustc -Vv
        cargo -V
      shell: bash

    - name: Bench
      run: cargo bench --target ${{ matrix.target }}
      shell: bash